### ISSUE TITLE
Question on Fortigate needing hostname for Graylog

### ISSUE THREAD

**Issue by ghost** [seanthegeek/graylog-fortigate-cef#1]
Hi there!

This is a great contribution for Fortigate/Graylog users. May I ask why the Fortigate needs the syslog server's hostname vs. an IP? The README's example is not using certs, so I am failing to understand how the hostname is qualified other than a DNS lookup.

Thanks!

**Comment by aman207** [comment]
Using an IP with no TLS worked fine for me
