### ISSUE TITLE
Installing content pack failed with status: FetchError: There was an error fetching a resource: Internal Server Error. Additional information: Failed to install content pack <af84f707-7473-4258-bb2a-9d9617247bdd/16>. Could not install Content Pack with ID: af84f707-7473-4258-bb2a-9d9617247bdd

### ISSUE THREAD

**Issue by Agipa** [seanthegeek/graylog-fortigate-cef#3]
Hello!
I can not install your pack. My graylog version 4.2.9 and have followed Readme of your pack. But get this error
>Installing content pack failed with status: FetchError: There was an error fetching a resource: Internal Server Error. Additional information: Failed to install content pack <af84f707-7473-4258-bb2a-9d9617247bdd/16>. Could not install Content Pack with ID: af84f707-7473-4258-bb2a-9d9617247bdd

Also attach my server.log. Please can ypu help me, I can not figure out what is problem?

>Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Missing Stream for widget entity
        >at org.graylog2.contentpacks.model.entities.WidgetEntity.lambda$toNativeEntity$1(WidgetEntity.java:151) ~[graylog.jar:?]
        >at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312]
        >at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312]
        >at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312]
        >at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580) ~[?:1.8.0_312]
        >at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312]
        >at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312]
        >at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_312]
        >at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312]
        >at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_312]
        >at org.graylog2.contentpacks.model.entities.WidgetEntity.toNativeEntity(WidgetEntity.java:159) ~[graylog.jar:?]
        >at org.graylog2.contentpacks.model.entities.ViewStateEntity.lambda$toNativeEntity$0(ViewStateEntity.java:125) ~[graylog.jar:?]
        >at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312]

**Comment by andrewm659** [comment]
Same.

**Comment by Mnchstrcityblues79** [comment]
Reverting Line 4361 of  the .json file to "90b14dff-7b80-400b-9913-7122a50a87e4" seems to clear the error.

**Comment by Agipa** [comment]
> Reverting Line 4361 of the .json file to "90b14dff-7b80-400b-9913-7122a50a87e4" seems to clear the error.

Thank you, dear @Mnchstrcityblues79 . It works now!!!
