### ISSUE TITLE
Can not  install pack: Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Missing Stream for widget entity

### ISSUE THREAD

**Issue by ducna96** [seanthegeek/graylog-fortigate-cef#4]
Hi, my friend,
I can't  install your content pack,  below is my log error,
How can I resolve it? 
many thanks.
[log.txt](https://github.com/seanthegeek/graylog-fortigate-cef/files/9286865/log.txt)

**Comment by seanthegeek** [comment]
Try the version I just uploaded

**Comment by ducna96** [comment]
thank you so much
